import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube} from 'react-icons/ai';
import Image from 'next/image';
import deved from '../public/dev-ed-wave.png';
import design from '../public/design.png'
import code from '../public/code.png'
import consulting from '../public/consulting.png'
import web1 from '../public/web1.png'
import web2 from '../public/web2.png'
import web3 from '../public/web3.png'
import web4 from '../public/web4.png'
import web5 from '../public/web5.png'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portifolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  
      <main className=' bg-white px-10 md:px-20 lg:px-40'>
        <section className="h-screen">
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-md font-burtons'>Developed by Keliton</h1>
            <ul className='flex items-center'>
              <li>
              </li>
                <BsFillMoonStarsFill className='cursor-pointer text-2xl'/>
              <li>
                <a className='bg-gradient-to-r from-cyan-500 bg-cyan-300 px-4 py-2 border-none rounded-md' href='#'>Resume</a>
              </li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-600 font-medium text-teal-600 md:text-6xl '>Keliton Vougan</h2>
            <h3 className='text-2xl py-2 md:text-3xl'>Texto 3</h3>
            <p className='text-medium py-5 leading-8 text-gray-800 md-text-xl max-w-lg mx-auto'>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <AiFillTwitterCircle/>
            <AiFillLinkedin/>
            <AiFillYoutube/>
          </div>
          <div className='relative bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 mx-auto overflow-hidden md:h-96 md:w-96'>
            <Image src={deved} layout='fill' objectFit='cover'/>
          </div>
        </section>

        <section>
          <div>
            <h3 className='text-3xl py-1'>Services I offer</h3>
            <p className='text-md py-2 leading-8 text-gray-800'>Lorem Ipsum is simply dummy text of the printing and typesetting industry
              <spam className='text-teal-500'>EXEMPLO</spam>
              printing and typesetting industry</p>
            <p className='text-md py-2 leading-8 text-gray-800'>Lorem Ipsum is simply dummy text of the printing and typesetting industry</p>
          </div>
          
          <div>
            <div className='text-center shadow-lg p-10 roundend-xl my-10'>
              <Image src={design} width={100} height={100}/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Beatiful Designs</h3>
              <p>
                Creating elegant designs suited for you
              </p>
              <h4 className='py-4 text-teal-600'>Desing tools I use</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>
           
            <div className='text-center shadow-lg p-10 roundend-xl my-10'>
              <Image src={code} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Beatiful Designs</h3>
              <p>
                Creating elegant designs suited for you
              </p>
              <h4 className='py-4 text-teal-600'>Desing tools I use</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>
            
            <div className='text-center shadow-lg p-10 roundend-xl my-10'>
              <Image src={consulting} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Beatiful Designs</h3>
              <p>
                Creating elegant designs suited for you
              </p>
              <h4 className='py-4 text-teal-600'>Desing tools I use</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>
          </div>
        </section>
       
        <section>
        <div>
            <h3 className='text-3xl py-1'>Portifolio</h3>
            <p className='text-md py-2 leading-8 text-gray-800'>Lorem Ipsum is simply dummy text of the printing and typesetting industry
              <spam className='text-teal-500'>EXEMPLO</spam>
              printing and typesetting industry</p>
            <p className='text-md py-2 leading-8 text-gray-800'>Lorem Ipsum is simply dummy text of the printing and typesetting industry</p>
        </div>
  
        <div>
          <Image src={web1}/>
        </div>
  
        <div>
          <Image src={web2}/>
        </div>
    
        <div>
          <Image src={web3}/>
        </div>

        <div>
          <Image src={web4}/>
        </div>
        
        <div>
          <Image src={web5}/>
        </div>
        </section>
      </main>
    </div>
  )
}
